# Generated by Django 5.2.8 on 2025-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=100, unique=True)),
                ('company_password', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_allocated_person', models.CharField(max_length=100)),
                ('review_person', models.CharField(max_length=100)),
                ('quickbook_status', models.CharField(max_length=100)),
                ('select_year', models.IntegerField(default=2025)),
                ('months', models.JSONField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
