# Generated by Django 5.2.8 on 2025-11-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='select_year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='client',
            name='account_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='quickbook_status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending'), ('data_provided', 'Data Provided by Client')], max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
