# Generated by Django 5.2.8 on 2025-11-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_select_year_client_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='months',
            field=models.JSONField(default=dict),
        ),
    ]
