# Generated by Django 5.2.8 on 2025-11-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.JSONField(default=list),
        ),
    ]
