# Generated by Django 5.2.8 on 2025-11-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='months',
        ),
        migrations.AddField(
            model_name='client',
            name='account_months',
            field=models.JSONField(default=dict),
        ),
    ]
