# Generated by Django 5.2.8 on 2025-12-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_client_account_months_client_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company_password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='quickbook_status',
        ),
    ]
