# Generated by Django 5.2.8 on 2025-12-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_client_company_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='months',
            new_name='year_months',
        ),
        migrations.RemoveField(
            model_name='client',
            name='year',
        ),
    ]
