# Generated by Django 5.2.8 on 2025-12-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_months_client_year_months_remove_client_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='year_months',
            new_name='months',
        ),
        migrations.AddField(
            model_name='client',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
