# Generated by Django 5.2.8 on 2025-12-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_year_months_client_months_client_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_allocated_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='review_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
