# Generated by Django 5.2.8 on 2025-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invitation_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
