# Generated by Django 5.2.8 on 2025-12-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_invitation_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
