# """
# Django settings for msystem project.

# Generated by 'django-admin startproject' using Django 5.2.8.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# import os


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-cgorbts%nxylx64gw#hsm)ko8yetllpn-07e#b&-9w%1a7)edy'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
# ALLOWED_HOSTS = ['your-ec2-public-ip', 'your-domain.com']


# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'msystem.urls'


# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Ensure this path is correct
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]


# WSGI_APPLICATION = 'msystem.wsgi.application'


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'msystemdb',
#         'USER': 'msystemuser',
#         'PASSWORD': 'Kirtan@2003',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True
# LOGIN_URL = 'login'


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/
# STATIC_URL = 'static/'


# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     # third-party
#     'import_export',
#     'core',
#     'rest_framework',
# ]


# from pathlib import Path
# BASE_DIR = Path(__file__).resolve().parent.parent
# TEMPLATES[0]['DIRS'] = [ BASE_DIR / 'templates' ]
# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static'
# ]
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Use SMTP backend for email
# EMAIL_HOST = 'smtp.gmail.com'  # Gmail's SMTP server
# EMAIL_PORT = 587  # Use port 587 for TLS
# EMAIL_USE_TLS = True  # Use TLS encryption for secure email sending
# EMAIL_HOST_USER = 'krish3na0@gmail.com'  # Your Gmail address
# EMAIL_HOST_PASSWORD = 'kcmjvalfjhauhnzw'
# DEFAULT_FROM_EMAIL = 'krish3na0@gmail.com'  # Default email address to send from


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django.template': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }



"""
Django settings for msystem project.

This settings file is prepared for both local development and Heroku deployment.
It prefers environment variables (for production) but falls back to the local
Postgres configuration you had so your app keeps working locally.
"""

from pathlib import Path
import os
import dj_database_url

# BASE_DIR
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------------------
# SECRET_KEY: read from env for production. A default dev key is provided so
# the project runs locally if you don't set SECRET_KEY in the environment.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-cgorbts%nxylx64gw#hsm)ko8yetllpn-07e#b&-9w%1a7)edy"  # dev fallback only
)

# DEBUG: set via env var. Default True locally to avoid unexpected silent failures.
DEBUG = os.environ.get("DEBUG", "True") == "True"

# ALLOWED_HOSTS: use comma-separated env var on production; default local hosts
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS").split(",") if h.strip()]
else:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ------------------------------------------------------------------------------
# INSTALLED APPS
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party
    'import_export',
    'rest_framework',

    # local apps
    'core',
]

# ------------------------------------------------------------------------------
# MIDDLEWARE (include WhiteNoise for static files)
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------------------------------------------
# URL and WSGI
# ------------------------------------------------------------------------------
ROOT_URLCONF = 'msystem.urls'
WSGI_APPLICATION = 'msystem.wsgi.application'

# ------------------------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # keep your existing templates directory
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ------------------------------------------------------------------------------
# DATABASES
# - Use DATABASE_URL (Heroku) if present.
# - Otherwise fall back to your local Postgres configuration so things keep working.
# ------------------------------------------------------------------------------
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Heroku (or other) provided DATABASE_URL
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    }
else:
    # Fallback to your previous local Postgres settings (so replacing this file
    # won't break your local dev). You can change these values if needed.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'msystemdb'),
            'USER': os.environ.get('POSTGRES_USER', 'msystemuser'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'Kirtan@2003'),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }

# ------------------------------------------------------------------------------
# AUTH PASSWORD VALIDATORS
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------------
# STATIC FILES
# ------------------------------------------------------------------------------
STATIC_URL = '/static/'

# Where collectstatic will put static files (Heroku expects this)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Your project's static folder
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise storage — will raise if static references are missing.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ------------------------------------------------------------------------------
# MEDIA (if you later add file uploads, use S3; Heroku filesystem is ephemeral)
# ------------------------------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ------------------------------------------------------------------------------
# EMAIL SETTINGS (read from environment; set on Heroku)
# ------------------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')   # set as Heroku config var
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # set as Heroku config var
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ------------------------------------------------------------------------------
# LOGIN / AUTH
# ------------------------------------------------------------------------------
LOGIN_URL = 'login'

# ------------------------------------------------------------------------------
# Django default primary key field
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------------------
# Additional security settings when DEBUG is False
# ------------------------------------------------------------------------------
if not DEBUG:
    # Heroku runs behind a proxy; let Django know
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Optionally force cookies to be secure (recommended for production)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Optional: set HSTS (enable if you know how to manage it)
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True

# ------------------------------------------------------------------------------
# Logging (keeps your existing config but it's useful on Heroku)
# ------------------------------------------------------------------------------
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'django.template': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': True},
    },
}
